# Welcome. Evergreen configuration can be time consuming to modify and test.
# So each script has a header comment describing how to run it locally.
#
# Some environment variables are hidden by ${inject_env_from_evergreen}.
# This is set in the evergreen project.
# View this in Evergreen => Projects => libmongocrypt.
#
functions:
  "fetch source":
    - command: git.get_project
      params: {directory: libmongocrypt}
    - command: shell.exec
      params:
        script: |-
          set -o errexit
          chmod u+x libmongocrypt/.evergreen/*.sh
          ./libmongocrypt/.evergreen/print-env-info.sh

  "tar and upload libmongocrypt libraries":
    - command: archive.targz_pack
      params:
        target: libmongocrypt.tar.gz
        source_dir: install/libmongocrypt
        include: [./**]
    - command: s3.put
      params:
        aws_key: '${aws_key}'
        aws_secret: '${aws_secret}'
        remote_file: '${libmongocrypt_s3_path}'
        bucket: mciuploads
        permissions: public-read
        local_file: 'libmongocrypt.tar.gz'
        content_type: '${content_type|application/x-gzip}'

tasks:
- name: build-and-test
  commands:
  - func: "fetch source"
  - command: "shell.exec"
    params:
      script: |-
        eval "${inject_env_from_evergreen}"
        ./libmongocrypt/.evergreen/compile.sh
        ./libmongocrypt/.evergreen/test.sh

  - func: "tar and upload libmongocrypt libraries"

pre:
  # Update the evergreen expansion to dynamically set the ${libmongocrypt_s3_path} expansion.
  # If this is a patch build, we want a URL specific to the patch, like:
  # /mciuploads/libmongocrypt/ubuntu1604/24411/build-and-test/libmongocrypt_ubuntu1604_24411/libmongocrypt.tar.gz
  # If this is a waterfall build, we want a fixed "latest" URL, like:
  # /mciuploads/libmongocrypt/ubuntu1604/latest/libmongocrypt.tar.gz
  - command: "shell.exec"
    params:
      script: |-
        REMOTE_PATH="${project}/${build_variant}/latest/libmongocrypt.tar.gz"
        if [ "${is_patch}" = "true" ]; then
           REMOTE_PATH="${project}/${build_variant}/${revision}/${task_name}/${build_id}/libmongocrypt.tar.gz"
        fi
        echo "libmongocrypt_s3_path: $REMOTE_PATH"
        echo "libmongocrypt_s3_path: $REMOTE_PATH" > expansion.yml
  - command: expansions.update
    params:
      file: expansion.yml

buildvariants:
- name: ubuntu1604
  display_name: "Ubuntu 16.04"
  run_on: ubuntu1604-test
  tasks:
  - build-and-test
- name: rhel76
  display_name: "RHEL 7.6"
  run_on: rhel76-test
  tasks:
  - build-and-test
- name: macos
  display_name: "macOS 10.14"
  run_on: macos-1014
  tasks:
  - build-and-test
- name: rhel72-zseries-test
  display_name: "RHEL 7,2 on zSeries"
  run_on: rhel72-zseries-test
  tasks:
  - build-and-test